name: 'Git Sync'
description: 'Git Sync enables you to synchronize code to any other Git repository'

branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  target-url:
    description: 'Target Repo URL'
    required: true
  target-username:
    description: 'Target Repo Username'
    required: true
  target-token:
    description: 'Target Token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create all branches locally
      run: |
        git branch -a | sed -n "/\/HEAD /d; /remotes/p;" | grep -v ${GITHUB_REF##*/} | xargs -L1 git checkout -t
      shell: bash
    - name: Disable LFS locking
      run: git config lfs.locksverify false
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.target-url }}
        INPUT_TARGET_USERNAME: ${{ inputs.target-username }}
        INPUT_TARGET_TOKEN: ${{ inputs.target-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}

